## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
title = "Michelle Weirathmueller's personal site"

# Explicitly enable all kinds
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "false"
#canonifyURLs = "true"

# Local
baseURL = "https://michw.com/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Michelle Weirathmueller's personal site"

[Params.social]

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]