name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # This is where your pre-built site is located
          publish_branch: gh-pages  # Change this if you want to use a different branch